name: Terraform Infrastructure Provision and App Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write      

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

    - name: Terraform Init
      run: terraform init
 
  trigger-frontend-backend:
    needs: terraform
    runs-on: ubuntu-latest
    steps: 
      - name: Trigger Frontend Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.DEPLOY_TOKEN }}" \
            -d '{"event_type": "deploy"}' \
            https://api.github.com/repos/sunnyk59/pas-frontend/dispatches